#
x_bot_core:
  name: XBotCore_basic

ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 0
  power_off_boards: false
  create_pipes: true

# Test LOW POW ESC 1
LpESC_1:
  sign: -1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]

# Test LOW POW ESC 2
LpESC_2:
  sign: -1
  pos_offset: 0
  pid :
    position: [20.0 , 0.0 , 1.0]
    
# Test HIGH POW ESC 123
HpESC_123:
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [800.0, 0.0, 5.0]

